{
 "title": "CoreDNS",
 "time": { "from": "2025-03-05T01:53:38.877Z", "to": "2025-03-05T02:15:01.918Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "clickhouse_datasource", "query": "grafana-clickhouse-datasource" },
   {
    "name": "client_ip",
    "query": "select distinct client_ip from dns_logs_mv"
   },
   {
    "name": "rcode",
    "query": "select distinct rcode from dns_logs_mv"
   },
   {
    "name": "name",
    "query": "select distinct name from dns_logs_mv"
   }
  ]
 },
 "panels": [
  {
   "title": "p90 Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n    quantile(0.9)(duration_secs) as p90,\n    toStartOfMinute(Time) AS minute\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode}) AND rcode IN (${rcode})\nGROUP BY minute\nORDER BY minute DESC"
    }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    count() as queries,\n    toStartOfMinute(Time) AS minute\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode})\nGROUP BY minute\nORDER BY minute DESC"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "count(NOERROR) / count()",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfMinute(Time) AS minute,\n    countIf(rcode != 'NOERROR') / count() AS error_rate\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode})\nGROUP BY minute\nORDER BY minute"
    }
   ]
  },
  {
   "title": "DSNSEC Failures",
   "type": "timeseries",
   "description": "count(DNSSEC_OK) / count()",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfMinute(Time) AS minute,\n    countIf(dnssec_ok) / count() AS error_rate\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode})\nGROUP BY minute\nORDER BY minute"
    }
   ]
  },
  {
   "title": "Count by Type",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    type,\n    count() AS count\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode})\nGROUP BY type\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Count by Client IP",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    client_ip,\n    count() AS count\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode})\nGROUP BY client_ip\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Count by Rcode",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    rcode,\n    count() AS count\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode})\nGROUP BY rcode\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Count by Rcode",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    rcode,\n    count() AS count\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode})\nGROUP BY rcode\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Used DNSSEC",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    dnssec_ok,\n    count() AS count\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode})\nGROUP BY dnssec_ok\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Count by Type",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "-- Group by minute first, then show top names for each time period\nSELECT\n    toStartOfMinute(Time) AS minute,\n    name,\n    count() AS count\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode}) AND rcode != 'NOERROR'\nGROUP BY minute, name\nORDER BY minute ASC, count DESC"
    }
   ]
  },
  {
   "title": "Count by Type",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "rawSql": "-- Group by minute first, then show top names for each time period\nSELECT\n    toStartOfMinute(Time) AS minute,\n    client_ip,\n    count() AS count\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode}) AND rcode != 'NOERROR'\nGROUP BY minute, client_ip\nORDER BY minute ASC, count DESC"
    }
   ]
  },
  {
   "title": "Count by Client IP Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n    client_ip,\n    toStartOfMinute(Time) AS minute,\n    count() AS count\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode})\nGROUP BY client_ip, minute\nORDER BY minute, count DESC"
    }
   ]
  },
  {
   "title": "Count by Name over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n    name,\n    toStartOfMinute(Time) AS minute,\n    count() AS count\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode})\nGROUP BY name, minute\nORDER BY minute, count DESC"
    }
   ]
  },
  {
   "title": "Count by Name over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT\n    rcode,\n    toStartOfMinute(Time) AS minute,\n    count() AS count\nFROM dns_logs_mv\nWHERE client_ip IN (${client_ip}) AND name IN (${name}) AND rcode IN (${rcode})\nGROUP BY rcode, minute\nORDER BY minute, count DESC"
    }
   ]
  }
 ]
}