receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${target_ip}:4317

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 30s
        static_configs:
        - targets: ['${target_ip}:8888']

  journald:
    directory: /run/log/journal
    units:
      - ssh
      - ${systemd_unit}
    priority: info

processors:
  batch:

exporters:
  otlp:
    endpoint: otelcol.jds.net:4317
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    timeout: 30s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

    logs:
      receivers: [journald]
      processors: [batch]
      exporters: [otlp]
