receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${target_ip}:4317

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 30s
        static_configs:
        - targets: ['${target_ip}:8888']

  journald:
    directory: /run/log/journal
    units:
      - ssh
      - ${systemd_unit}
    priority: info

processors:
  batch:

exporters:
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [debug]
