bpf:
  masquerade: true
  vlanBypass:
  - 0
cluster:
  name: kubernetes
enableIPv4Masquerade: true
enableIdentityMark: true
gatewayAPI:
  enabled: true
hostPort:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  export:
    static:
      enabled: true
      filePath: "/var/run/cilium/hubble/events.log"
ingressController:
  default: true
  loadbalancerMode: dedicated
ipam:
  mode: cluster-pool
k8sClientRateLimit:
  burst: 15
  qps: 10
k8sServiceHost: ${kubernetes_server_ip}
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
l7Proxy: true
loadBalancer:
  l7:
    backend: envoy
operator:
  prometheus:
    enabled: true
  replicas: 1
prometheus:
  enabled: true
routingMode: tunnel
tunnelProtocol: vxlan
